language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt

script:
  - pytest --driver Chrome

addons:
  apt:
    packages:
      - chromium-browser
      - chromium-chromedriver
