language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt

before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/

script:
  - pytest --driver Chrome

addons:
  apt:
    packages:
      - chromium-chromedriver
      - google-chrome-stable

    sources:
      - google-chrome
