language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt

before_script:
  - export PATH=$PATH:$HOME/bin

before_install:
  - wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip -O /tmp/chromedriver.zip
  - unzip /tmp/chromedriver.zip -d $HOME/bin

script:
  - pytest --driver Chrome

addons:
  apt:
    packages:
      - google-chrome-stable

    sources:
      - google-chrome
