language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt

before_script:
  - export PATH=$PATH:$HOME/bin

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz -O /tmp/geckodriver.tar.gz
  - mkdir $HOME/bin
  - tar zxf /tmp/geckodriver.tar.gz -C $HOME/bin

script:
  - pytest --driver Firefox

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
